set(CMAKE_BUILD_TYPE Release CACHE STRING "")
set(LLVM_ENABLE_ASSERTIONS On CACHE BOOL "")
set(LLVM_BUILD_EXTERNAL_COMPILER_RT On CACHE BOOL "")
set(LLVM_TARGETS_TO_BUILD X86 ARM AArch64 CACHE STRING "")
set(LLVM_BUILD_TESTS On CACHE BOOL "")

set(LLVM_LIT_ARGS "--xunit-xml-output=testresults.xunit.xml -v" CACHE STRING "")
