set(LLVM_ENABLE_PROJECTS "clang" CACHE STRING "")
set(LLVM_TARGETS_TO_BUILD AArch64 CACHE STRING "")
set(CMAKE_BUILD_TYPE Debug CACHE STRING "")

set(LLVM_USE_SANITIZER "Address;Undefined" CACHE STRING "")
set(LLVM_OPTIMIZE_SANITIZED_BUILDS Off CACHE BOOL "")
