set(CMAKE_BUILD_TYPE RelWithDebInfo CACHE STRING "")
set(LLVM_ENABLE_ASSERTIONS On CACHE BOOL "")
set(CMAKE_C_FLAGS_RELWITHDEBINFO "-O3 -DNDEBUG" CACHE STRING "")
set(CMAKE_CXX_FLAGS_RELWITHDEBINFO "-O3 -DNDEBUG" CACHE STRING "")
