set(LLVM_VERSION_SUFFIX "o3" CACHE STRING "")

set(CMAKE_C_FLAGS_RELWITHDEBINFO "-O3 -DNDEBUG" CACHE STRING "")
set(CMAKE_CXX_FLAGS_RELWITHDEBINFO "-O3 -DNDEBUG" CACHE STRING "")

include(${CMAKE_CURRENT_LIST_DIR}/../Stage2-Base.cmake)
