set(LLVM_VERSION_SUFFIX "lto" CACHE STRING "")

set(LLVM_ENABLE_LTO ON CACHE BOOL "")
set(CMAKE_C_FLAGS_RELWITHDEBINFO "-O3 -gline-tables-only -DNDEBUG" CACHE STRING "")
set(CMAKE_CXX_FLAGS_RELWITHDEBINFO "-O3 -gline-tables-only -DNDEBUG" CACHE STRING "")

include(${CMAKE_CURRENT_LIST_DIR}/../Stage2-Base.cmake)
